version: '3.8'

services:

  cli-init-ssm.bc-coop.bclan:
    container_name: cli-init-ssm-bclan-${DOCKER_NETWORK}
    image: ${DOCKER_REPOSITORY}c2-sandbox-cli:${VERSION_C2}
    command: /opt/c2-sandbox/chaincode/ssm/init.sh
    networks:
      - net

networks:
  net:
    name: ${DOCKER_NETWORK}
    external: true
